"""neural_harness CLI.

  nh list                         list known project adapters
  nh validate <project>           run the full harness for one project
                                  (project = demo | celebrum | samvit |
                                             collabuild | all)
  nh voice "<text>"               grade any text's human voice index
  nh voice --file report.md       grade a file
  nh site --root DIR              evaluate every local project and write one
                                  combined report for tomorrow's review
"""

from __future__ import annotations

import argparse
import os
import sys


def _validate(project: str, root_dir: str, out_dir: str) -> dict:
    from .projects import run_project
    from .report import build_report, to_markdown
    harness, results, fused = run_project(project, root_dir)
    report = build_report(harness, results, fused)
    print()
    print(report["prose"])
    print()
    voice = report["voice"]
    print(f"[voice] human index {voice['human_voice_index']:.3f} -> {voice['label']}")
    if voice.get("notes"):
        print(f"[voice] tells: {'; '.join(voice['notes'])}")

    os.makedirs(out_dir, exist_ok=True)
    base = os.path.join(out_dir, f"{project}.validation")
    with open(base + ".json", "w") as f:
        import json
        json.dump({k: v for k, v in report.items() if k != "json"}, f, indent=2)
    with open(base + ".md", "w") as f:
        f.write(to_markdown(report))
    harness.save_history(os.path.join(out_dir, "harness_history.jsonl"))
    print(f"[wrote] {base}.json and {base}.md")
    return report


def _voice(args) -> None:
    from .airadio import rate_human_voice
    text = args.text
    if args.file:
        with open(args.file) as f:
            text = f.read()
    score = rate_human_voice(text)
    print(json_dumps(score.to_dict()))
    print(f"human voice index: {score.human_index:.3f} -> {score.label()}")


def json_dumps(obj) -> str:
    import json
    return json.dumps(obj, indent=2)


def _find_root() -> str:
    # this package lives under one of the project trees; default to the repo of
    # the caller's cwd so evaluators can run from inside a project.
    return os.getcwd()


def _default_out() -> str:
    return os.path.join(_find_root(), "harness_reports")


def main(argv=None) -> int:
    p = argparse.ArgumentParser(prog="nh", description=__doc__)
    sub = p.add_subparsers(dest="cmd")

    vl = sub.add_parser("validate", help="run the full harness for a project")
    vl.add_argument("project", nargs="?", default="demo",
                    help="demo | celebrum | samvit | collabuild | all")
    vl.add_argument("--root", default=None, help="project checkout directory")
    vl.add_argument("--out", default=None, help="report output directory")

    sp = sub.add_parser("site", help="evaluate every local project for tomorrow")
    sp.add_argument("--root", default="/root", help="directory containing checkouts")
    sp.add_argument("--out", default=None)

    ls = sub.add_parser("list", help="list known project adapters")
    vo = sub.add_parser("voice", help="grade human voice index of text")
    vo.add_argument("text", nargs="?", default=None)
    vo.add_argument("--file", default=None)

    args = p.parse_args(argv)
    cmd = args.cmd or "validate"
    root = getattr(args, "root", None) or _find_root()
    out = getattr(args, "out", None) or _default_out()

    if cmd == "list":
        from .projects import ALL
        print("\n".join(ALL))
        return 0
    if cmd == "voice":
        _voice(args)
        return 0
    if cmd == "site":
        from .projects import ALL
        from .report import to_markdown
        os.makedirs(out, exist_ok=True)
        combined = []
        for proj in ALL:
            proj_root = root if proj == "demo" else os.path.join(root, proj)
            try:
                r = _validate(proj, proj_root, out)
                combined.append(r)
                print(f"[ok] {proj}")
            except Exception as exc:
                print(f"[skip] {proj}: {exc!r}")
        # combined landing page for tomorrow's evaluation
        lines = [
            "# Cross-project evaluation - ready for tomorrow's review",
            "",
            "Every project below ran the same shared harness (information "
            "handling, neural synthesis, fused data integration). Each report "
            "was generated by the humanizer and graded by AiRadio.",
            "",
        ]
        for r in combined:
            s = r["summary"]
            v = r["voice"]
            lines += [
                f"## {r['project']}",
                "",
                f"- overall accuracy: **{s['overall_accuracy']:.3f}**",
                f"- integration accuracy: {s['integration_accuracy']}",
                f"- passed {s['passed']}/{s['total_checks']}, "
                f"warnings {s['warned']}, failures {s['failed']}",
                f"- human voice index: {v['human_voice_index']:.3f} "
                f"({v['label']})",
                "",
            ]
        landing = os.path.join(out, "ALL_EVALUATION.md")
        with open(landing, "w") as f:
            f.write("\n".join(lines))
        print(f"[wrote] {landing}")
        return 0

    # single validate
    _validate(args.project, root, out)
    return 0


if __name__ == "__main__":
    sys.exit(main())